### PR TITLE
Translate containers.md, text.md, icons.md into Korean

### PR DESCRIPTION
**Pull request by Baejw0111**
I'm sorry for the lack of updates recently 😥 I've been a little busy because the project I'm working on is nearing its end. I'll be back soon to update the translation work!

### CODE REVIEW

**Comment by Baejw0111** [comment]
By the way, the "SQL Tables" documentation states "If you hover over the primary key or foreign key with your cursor, you'll notice that the corresponding key is highlighted." Is this a function that actually works? This doesn't seem to work in D2 Playgrounds.

**Comment by Baejw0111** [comment]
Welcome back! Can you answer my last question?

**Comment by alixander** [comment]
@Baejw0111 oh you're right, that's only in the D2 Studio IDE. I've[ removed it](https://github.com/terrastruct/d2-docs/commit/984dcb0dabb1a0fafa7f659efab28c6cf4284256) from the doc page and will deploy it soon

**Comment by Baejw0111** [comment]
@alixander Oh I got it! Thanks to reply!

**Pull request merged**
