### PR TITLE
Translate several pages into Korean

### PR DESCRIPTION
**Pull request by Baejw0111**
Long time no see! Sorry for the lack of updates for a long time. There was a program I was participating in that ended and I took a bit of a long break. I'll see you again often!

### CODE REVIEW

**Review by alixander — COMMENTED** [review]
@Baejw0111 thank you for this, truly appreciate it 🙏 

I made a rather big refactor recently that links all the D2 code snippets to be all from one place instead of repeating it.

https://github.com/terrastruct/d2-docs/pull/203/files#diff-6c691c53270128394a5d4fee3d772141779a0dc3acb83acc49d0954241a6ab6eR1

Would it be possible to include that refactor here too? That way when any code changes, it changes for both the english and korean versions without having to update multiple places.

**Comment by Baejw0111** [comment]
Oh, I see. When I work on translation, only the English part will be changed to Korean, so the code with refactoring will be included in the translation. I will add the documents that have already been translated separately.

**Comment by Baejw0111** [comment]
Please review

**Review by alixander — APPROVED** [review]
Thanks very much 👍 , and sorry for the delay. I think the Korean version is almost there as the first translation of D2's documentation! 

I'm not sure why when I render in Korean, there's two missing assets in the home page.

Screenshot 2024-05-02 at 3 45 34 PM

Probably not related to this PR though, so not blocking, just noting.

**Pull request merged**
