### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by deining**
This PR fixes a few typos I spotted. It also corrects a chemical equation which was not printed properly.

### CODE REVIEW

**Review by alixander — CHANGES_REQUESTED** [review]
thanks for doing this! `LaTex` -> `LaTeX` please

**Comment by deining** [comment]
> thanks for doing this!

You are welcome!

> `LaTex` -> `LaTeX` please

Yes, of course. Changed as requested.

**Comment by deining** [comment]
My commit is signed-off now, as requested.
Note: as a minor additional amendment, I bumped `actions/cache` version in GitHub workflow files to latest version `v3`.

**Review by alixander — APPROVED** [review]
thanks!

**Pull request merged**
